// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: supplychain/actorscontract.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Actorscontract struct {
	Index      string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	ContractId string `protobuf:"bytes,2,opt,name=contractId,proto3" json:"contractId,omitempty"`
	Owner      string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Vendor     string `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Commission uint64 `protobuf:"varint,5,opt,name=commission,proto3" json:"commission,omitempty"`
}

func (m *Actorscontract) Reset()         { *m = Actorscontract{} }
func (m *Actorscontract) String() string { return proto.CompactTextString(m) }
func (*Actorscontract) ProtoMessage()    {}
func (*Actorscontract) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba0ab82c4e790af3, []int{0}
}
func (m *Actorscontract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Actorscontract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Actorscontract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Actorscontract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actorscontract.Merge(m, src)
}
func (m *Actorscontract) XXX_Size() int {
	return m.Size()
}
func (m *Actorscontract) XXX_DiscardUnknown() {
	xxx_messageInfo_Actorscontract.DiscardUnknown(m)
}

var xxx_messageInfo_Actorscontract proto.InternalMessageInfo

func (m *Actorscontract) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Actorscontract) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *Actorscontract) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Actorscontract) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Actorscontract) GetCommission() uint64 {
	if m != nil {
		return m.Commission
	}
	return 0
}

func init() {
	proto.RegisterType((*Actorscontract)(nil), "upalchowdhury.supplychain.supplychain.Actorscontract")
}

func init() { proto.RegisterFile("supplychain/actorscontract.proto", fileDescriptor_ba0ab82c4e790af3) }

var fileDescriptor_ba0ab82c4e790af3 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x2e, 0x2d, 0x28,
	0xc8, 0xa9, 0x4c, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0x4c, 0x2e, 0xc9, 0x2f, 0x2a, 0x4e, 0xce,
	0xcf, 0x2b, 0x29, 0x4a, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x2d, 0x2d,
	0x48, 0xcc, 0x49, 0xce, 0xc8, 0x2f, 0x4f, 0xc9, 0x28, 0x2d, 0xaa, 0xd4, 0x43, 0x52, 0x8f, 0xcc,
	0x56, 0x9a, 0xc2, 0xc8, 0xc5, 0xe7, 0x88, 0xa2, 0x5f, 0x48, 0x84, 0x8b, 0x35, 0x33, 0x2f, 0x25,
	0xb5, 0x42, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x11, 0x92, 0xe3, 0xe2, 0x82, 0xa9,
	0xf0, 0x4c, 0x91, 0x60, 0x02, 0x4b, 0x21, 0x89, 0x80, 0x74, 0xe5, 0x97, 0xe7, 0xa5, 0x16, 0x49,
	0x30, 0x43, 0x74, 0x81, 0x39, 0x42, 0x62, 0x5c, 0x6c, 0x65, 0xa9, 0x79, 0x29, 0xf9, 0x45, 0x12,
	0x2c, 0x60, 0x61, 0x28, 0x0f, 0x62, 0x5a, 0x6e, 0x6e, 0x66, 0x71, 0x71, 0x66, 0x7e, 0x9e, 0x04,
	0xab, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x92, 0x88, 0x53, 0xd0, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e,
	0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37,
	0x1e, 0xcb, 0x31, 0x44, 0x59, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea,
	0xa3, 0x78, 0x51, 0x1f, 0x39, 0x48, 0x2a, 0x50, 0x78, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c,
	0xe0, 0x80, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x46, 0x17, 0xd5, 0xfc, 0x3c, 0x01, 0x00,
	0x00,
}

func (m *Actorscontract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Actorscontract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Actorscontract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Commission != 0 {
		i = encodeVarintActorscontract(dAtA, i, uint64(m.Commission))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Vendor) > 0 {
		i -= len(m.Vendor)
		copy(dAtA[i:], m.Vendor)
		i = encodeVarintActorscontract(dAtA, i, uint64(len(m.Vendor)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintActorscontract(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContractId) > 0 {
		i -= len(m.ContractId)
		copy(dAtA[i:], m.ContractId)
		i = encodeVarintActorscontract(dAtA, i, uint64(len(m.ContractId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintActorscontract(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintActorscontract(dAtA []byte, offset int, v uint64) int {
	offset -= sovActorscontract(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Actorscontract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovActorscontract(uint64(l))
	}
	l = len(m.ContractId)
	if l > 0 {
		n += 1 + l + sovActorscontract(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovActorscontract(uint64(l))
	}
	l = len(m.Vendor)
	if l > 0 {
		n += 1 + l + sovActorscontract(uint64(l))
	}
	if m.Commission != 0 {
		n += 1 + sovActorscontract(uint64(m.Commission))
	}
	return n
}

func sovActorscontract(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozActorscontract(x uint64) (n int) {
	return sovActorscontract(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Actorscontract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorscontract
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Actorscontract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Actorscontract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorscontract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorscontract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActorscontract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorscontract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorscontract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActorscontract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorscontract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorscontract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActorscontract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vendor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorscontract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorscontract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActorscontract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vendor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commission", wireType)
			}
			m.Commission = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorscontract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Commission |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActorscontract(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActorscontract
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipActorscontract(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowActorscontract
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActorscontract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActorscontract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthActorscontract
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupActorscontract
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthActorscontract
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthActorscontract        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowActorscontract          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupActorscontract = fmt.Errorf("proto: unexpected end of group")
)
